# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addmsg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x64\x64msg.proto\x12\x06wechat\"#\n\x11SKBuiltinString_t\x12\x0e\n\x06string\x18\x01 \x01(\t\"1\n\x11SKBuiltinBuffer_t\x12\x0c\n\x04iLen\x18\x01 \x02(\r\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\"\xe0\x02\n\x06\x41\x64\x64Msg\x12\r\n\x05msgId\x18\x01 \x02(\x05\x12/\n\x0c\x66romUserName\x18\x02 \x02(\x0b\x32\x19.wechat.SKBuiltinString_t\x12-\n\ntoUserName\x18\x03 \x02(\x0b\x32\x19.wechat.SKBuiltinString_t\x12\x0f\n\x07msgType\x18\x04 \x02(\x05\x12*\n\x07\x63ontent\x18\x05 \x02(\x0b\x32\x19.wechat.SKBuiltinString_t\x12\x0e\n\x06status\x18\x06 \x02(\r\x12\x11\n\timgStatus\x18\x07 \x02(\r\x12)\n\x06imgBuf\x18\x08 \x02(\x0b\x32\x19.wechat.SKBuiltinBuffer_t\x12\x12\n\ncreateTime\x18\t \x02(\r\x12\x11\n\tmsgSource\x18\n \x01(\t\x12\x13\n\x0bpushContent\x18\x0b \x01(\t\x12\x10\n\x08newMsgId\x18\x0c \x01(\x03\x12\x0e\n\x06msgSeq\x18\r \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addmsg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SKBUILTINSTRING_T._serialized_start=24
  _SKBUILTINSTRING_T._serialized_end=59
  _SKBUILTINBUFFER_T._serialized_start=61
  _SKBUILTINBUFFER_T._serialized_end=110
  _ADDMSG._serialized_start=113
  _ADDMSG._serialized_end=465
# @@protoc_insertion_point(module_scope)
